language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t moshempangea/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true moshempangea/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-232740359467"
  bucket_path: "docker-react"
  on:
    branch: master
